package com.kshetrajna.app.data.simulation

import com.kshetrajna.app.core.simulation.SimulationEngine
import com.kshetrajna.app.core.simulation.SimulationScenario
import com.kshetrajna.app.data.local.LocalDataSource

/**
 * Seeder populating [LocalDataSource] with deterministic scenario data generated by [SimulationEngine].
 */
class SimulatedDataSourceSeeder(
    val engine: SimulationEngine = SimulationEngine()
) {

    suspend fun seedScenario(
        localDataSource: LocalDataSource,
        scenario: SimulationScenario,
        steps: Int = 1
    ) {
        val farm = engine.generateFarm()
        localDataSource.insertFarm(farm)

        val cropProfile = engine.generateCropProfile()
        localDataSource.insertCropProfile(cropProfile)

        for (step in 0 until steps) {
            val node = engine.generateNode(scenario, step)
            localDataSource.insertNode(node)

            val reading = engine.generateSensorReading(node.id, scenario, step)
            localDataSource.insertSensorReading(reading)

            val weather = engine.generateWeatherData(farm.id, scenario, step)
            localDataSource.insertWeatherData(weather)

            val safety = engine.generateSafetyState(node.id, scenario, step)
            localDataSource.insertSafetyState(safety)

            val irrigationState = engine.generateIrrigationState(node.id, scenario, step)
            localDataSource.insertIrrigationState(irrigationState)

            val command = engine.generateIrrigationCommand(node.id, scenario, step)
            localDataSource.insertIrrigationCommand(command)

            val alert = engine.generateAlert(node.id, scenario, step)
            alert?.let { localDataSource.insertAlert(it) }

            val npk = engine.generateNpkResult(node.id, step)
            localDataSource.insertNpkResult(npk)

            engine.clock.advanceTimeBy(60_000L) // Advance simulation clock by 1 minute per step
        }
    }
}
